export const FETCH_VIDEOS_REQUEST = "FETCH_VIDEOS_REQUEST"
export const FETCH_VIDEOS_SUCCESS = "FETCH_VIDEOS_SUCCESS"
export const FETCH_VIDEOS_FAILURE = "FETCH_VIDEOS_FAILURE"  
export const VIDEOS_LIST_CLEARED = "VIDEOS_LIST_CLEARED"
export const VIDEOS_LIST_EMPTY = "VIDEOS_LIST_EMPTY"

export const THEME_MODE_CHANGE = "THEME_MODE_CHANGE"

export const QUERY_STRING_CHANGED = "QUERY_STRING_CHANGED"


