export const FETCH_VIDEOS_REQUEST = "FETCH_VIDEOS_REQUEST"
export const FETCH_VIDEOS_SUCCESS = "FETCH_VIDEOS_SUCCESS"
export const FETCH_VIDEOS_FAILURE = "FETCH_VIDEOS_FAILURE"  

export const THEME_LIGHT_MODE = "THEME_LIGHT"
export const THEME_DARK_MODE = "THEME_DARK"